spring:
  application:
    name: auth-server
server:
  port: 7777
  servlet:
    contextPath: /uaa #web基路径
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:118.25.123.16}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true